apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: le-security
  labels:
    app: keycloak
    project: linkedeye
type: Opaque
stringData:
  admin-password: LinkedEye@2026
  db-password: Keycloak@DB2026
